### ISSUE TITLE
Infografia de Hilos

### ISSUE THREAD

**Issue by Aricel117** [SistemasTecTlaxiaco/infografia-de-hilos-Aricel117#2]
[Infografia de Hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Aricel117/files/6520977/Infografia.de.Hilos.pdf)

**Comment by christopheremv** [comment]
calificación  19

**Comment by josealfredo79** [comment]
bien hecho y revisado
